1.FOOD ITEMS AND THIER CORRESPONDING PRICES

In [15]:
food_items <- c("waakye", "gari", "sphagetti","salad","egg", "meat")
food_items


[1] "waakye"    "gari"      "sphagetti" "salad"     "egg"       "meat"

In [16]:
prices <- c(4.0, 0.5,1.5,1.0,1.0,3.0)
prices

[1] 4.0 0.5 1.5 1.0 1.0 3.0

In [23]:
food_prices <- array(c(food_items,prices),dim = c(6,2))
food_prices

[,1]      [,2]
[1,] waakye    4   
[2,] gari      0.5 
[3,] sphagetti 1.5 
[4,] salad     1   
[5,] egg       1   
[6,] meat      3

 2.CREATING AN ARRAY OUT OF FOUR(4) LISTS.

In [24]:
phones <- list("Apple", "Samsung", "Huawei", "Rlg")
phones

[[1]]
[1] "Apple"

[[2]]
[1] "Samsung"

[[3]]
[1] "Huawei"

[[4]]
[1] "Rlg"

In [25]:
countries <- list("Amreica", "South Korea", "China","Ghana")
countries

[[1]]
[1] "Amreica"

[[2]]
[1] "South Korea"

[[3]]
[1] "China"

[[4]]
[1] "Ghana"

In [28]:
Average_prices <- list(600,400, 300, 100)
Average_prices

[[1]]
[1] 600

[[2]]
[1] 400

[[3]]
[1] 300

[[4]]
[1] 100

In [29]:
ranking <- list(3,2,1,4)
ranking

[[1]]
[1] 3

[[2]]
[1] 2

[[3]]
[1] 1

[[4]]
[1] 4

In [40]:
grade <- list("Best","Better","Good","Bad")
grade

[[1]]
[1] "Best"

[[2]]
[1] "Better"

[[3]]
[1] "Good"

[[4]]
[1] "Bad"

In [43]:
phone_list <- array(list(phones,countries,Average_prices,ranking,grade), dim = c(5,1))
phone_list

[,1]                                              
[1,] Apple  , Samsung, Huawei , Rlg                    
[2,] Amreica    , South Korea, China      , Ghana      
[3,] 600, 400, 300, 100                                
[4,] 3, 2, 1, 4                                        
[5,] Best  , Better, Good  , Bad

3. CREATE AN ARRAY OUT OF VECTORS, LISTS AND MATRIX

VECTORS

In [45]:
Presidents <- c("Akuffo Addo", "Trump", "Obama", "Mahama", "Buhari")
Presidents

[1] "Akuffo Addo" "Trump"       "Obama"       "Mahama"      "Buhari"

In [49]:
array_Presidents <- array(c(Precidents),dim = c(3,2))
array_Presidents

[,1]        [,2]       
[1,] Akuffo Addo Mahama     
[2,] Trump       Buhari     
[3,] Obama       Akuffo Addo

LISTS

In [50]:
cities <- list("Accra", "Kumasi",37,"Ho","LA", "NewYork", "Berlin", "Ottawa")
cities

[[1]]
[1] "Accra"

[[2]]
[1] "Kumasi"

[[3]]
[1] 37

[[4]]
[1] "Ho"

[[5]]
[1] "LA"

[[6]]
[1] "NewYork"

[[7]]
[1] "Berlin"

[[8]]
[1] "Ottawa"

In [53]:
cities_array <- array(list(cities), dim = c(4,1))
cities_array

[,1]                                                                  
[1,] Accra  , Kumasi , 37     , Ho     , LA     , NewYork, Berlin , Ottawa 
[2,] Accra  , Kumasi , 37     , Ho     , LA     , NewYork, Berlin , Ottawa 
[3,] Accra  , Kumasi , 37     , Ho     , LA     , NewYork, Berlin , Ottawa 
[4,] Accra  , Kumasi , 37     , Ho     , LA     , NewYork, Berlin , Ottawa

Matrix

In [64]:
Numbers <- matrix(1:100, nrow = 10, byrow = 10)
Numbers

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,]  1    2    3    4    5    6    7    8    9    10  
 [2,] 11   12   13   14   15   16   17   18   19    20  
 [3,] 21   22   23   24   25   26   27   28   29    30  
 [4,] 31   32   33   34   35   36   37   38   39    40  
 [5,] 41   42   43   44   45   46   47   48   49    50  
 [6,] 51   52   53   54   55   56   57   58   59    60  
 [7,] 61   62   63   64   65   66   67   68   69    70  
 [8,] 71   72   73   74   75   76   77   78   79    80  
 [9,] 81   82   83   84   85   86   87   88   89    90  
[10,] 91   92   93   94   95   96   97   98   99   100

In [66]:
Numbers_array <- array(matrix(Numbers), dim = c(20,5))
Numbers_array

[,1] [,2] [,3] [,4] [,5]
 [1,]  1    3    5    7     9 
 [2,] 11   13   15   17    19 
 [3,] 21   23   25   27    29 
 [4,] 31   33   35   37    39 
 [5,] 41   43   45   47    49 
 [6,] 51   53   55   57    59 
 [7,] 61   63   65   67    69 
 [8,] 71   73   75   77    79 
 [9,] 81   83   85   87    89 
[10,] 91   93   95   97    99 
[11,]  2    4    6    8    10 
[12,] 12   14   16   18    20 
[13,] 22   24   26   28    30 
[14,] 32   34   36   38    40 
[15,] 42   44   46   48    50 
[16,] 52   54   56   58    60 
[17,] 62   64   66   68    70 
[18,] 72   74   76   78    80 
[19,] 82   84   86   88    90 
[20,] 92   94   96   98   100